### PR TITLE
Removed IDisposable from MqttClientConnection class.

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes the issue from https://github.com/chkr1011/MQTTnet/pull/1284.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Fixes https://github.com/chkr1011/MQTTnet/issues/1292.

**Comment by chkr1011** [comment]
@SeppPenner I think this is the same as #1284 right?

**Comment by SeppPenner** [comment]
> 
> 
> @SeppPenner I think this is the same as #1284 right?

Yes, with the difference that I completely removed the IDisposable as you suggested. Just didn't want to add it directly to not break anything.

**Comment by chkr1011** [comment]
Thank you for your contribution. Good work.

**Pull request merged**
