### PR TITLE
initial version of ms.extensions.logging and di 

### PR DESCRIPTION
**Pull request by JanEggers**
wip for #65 (logging integrated no new packages)
logging should work
the clientid should be in the scope now so all logs for one client should share that scope. im not shure if server is working but client looks good

i guess some of the stuff in server options could also be moved into di.

i also need to update wiki...

### CODE REVIEW

**Comment by JanEggers** [comment]
i cant view the guideline i broke. it says only repository owner may view so please provide feedback so i can improve

**Comment by chkr1011** [comment]
Is it possible to support the static logging event? I use this in my projects. Also in the UWP app in this repo I use it to move all traces to a text box. Or can you migrate this code as well? 

We also have to update all Wiki entries after those changes are released 😄

**Comment by JanEggers** [comment]
> Is it possible to support the static logging event?

shure i can create a LoggerProvider. then you can do something like:

```
//in startup code
serviceProvider.GetService<ILoggerFactory>().AddCallbackLogger();

//in your view
CallbackLoggerProvider.OnLog += (log) => {}; 

```

is that good enough?

**Comment by chkr1011** [comment]
Sure something like this. I need an _easy_ way of just putting the traces somewhere.

**Comment by JanEggers** [comment]
oki i will add it

**Comment by chkr1011** [comment]
I also see no changes for the UniversalWindows library. Are there no changes at all or do don't migrate this project?

**Comment by JanEggers** [comment]
i added back the old api for consuming logs that should simplify migration.

> I also see no changes for the UniversalWindows library

i will have a look at them.  (I dont have that projects loaded because uwp sdk does not work for some reason.)

**Comment by chkr1011** [comment]
The problem is that some concepts of the core library are designed in the way they are to support UWP as well. Beside adapters and channel not that much but I am afraid that the new logging may break the UWP implementation.

**Comment by JanEggers** [comment]
uwp projects should also be up and running (at least they build but i cannot start em on my machine)

how does the github flow for wikis work i never updated one?

**Comment by chkr1011** [comment]
I gave you access as a contributor to this project. You can now create branches in this repository. But merging from develop to master is still my part 😄

**Comment by chkr1011** [comment]
I assume you can directly update the Wiki via "Edit" and commit the changes...

**Comment by chkr1011** [comment]
The new trace approach works for the UWP app. Visually no difference but I cannot set the client ID anymore. This was a new requested feature. Using the factory I cannot pass an identifier which let the user distinguish between several clients running in the same process. Or did I make a mistake while setting up the logging?

**Comment by JanEggers** [comment]
the information is there i create a LogScope for each client with its clientid. I was not able to port that Information to MqttTrace see https://github.com/chkr1011/MQTTnet/blob/3529724bdc91f6591fa91ca3c49c38b31a70e4e1/MQTTnet.Core/Diagnostics/MqttNetLogger.cs#L37

the information is stored in callcontext so it flows to all loggers in that scope. 
it should be visibile if you use serilog or ms.extensions.logging.console.

if you know how to port this let me know! i tried to view history of that file so i get the 1.1.2 version but i didnt get it compiling.
https://github.com/aspnet/Logging/blob/a42605cc0c51b36ac3dda10401e7ffea05c8d848/src/Microsoft.Extensions.Logging.Console/ConsoleLogScope.cs#L22

**Comment by chkr1011** [comment]
Ah there it is. OK. My initial implementation was detached from such protocol details. There you can specify a separate identifier. The use case was if a have 2 clients (also with the same ID) which are bridging two brokers I cannot distinguish. Is there any way to inject a separate ID like before with the factory constructor?

**Comment by JanEggers** [comment]
Adding a seperate property to MqttNetLogger would be possible but all other Libraries that interact with ILogger dont know it and so they wont use it, thats why i put it in the Scope. 

If a separate Id is required we can add it to the options and create the scope with that Id.

Using a factory with parameter would also be possible.

**Comment by chkr1011** [comment]
Mhh it's up to you 😄 I would prefer the options with an additional _LogId_ which falls back to the clientId if not set. Because this was a user request I also can only guess what makes sense. 😄

**Pull request merged**
