### PR TITLE
Added support for Net6.0.

### PR DESCRIPTION
**Pull request by SeppPenner**
Fixes https://github.com/chkr1011/MQTTnet/issues/1296 (I hope, I didn't forget anything).

### CODE REVIEW

**Comment by yyjdelete** [comment]
@SeppPenner 
See https://github.com/chkr1011/MQTTnet/pull/1135#issuecomment-812466126, since net6.0 already has an proper sdk, you can replace all `NET5_0` to `NET5_0_OR_GREATER` to avoid future changes for new targetFramework.

**Comment by SeppPenner** [comment]
> 
> 
> @SeppPenner See [#1135 (comment)](https://github.com/chkr1011/MQTTnet/pull/1135#issuecomment-812466126), since net6.0 already has an proper sdk, you can replace all (excepted the one in `TargetFrameworkProvider.cs`) `NET5_0` to `NET5_0_OR_GREATER` to avoid future changes for new targetFramework.

I will update this pull request soon with the changes :)

**Comment by chkr1011** [comment]
>I will update this pull request soon with the changes :)

Is this done?

**Comment by SeppPenner** [comment]
> > I will update this pull request soon with the changes :)
> 
> Is this done?

Not yet, I was quite busy (End of the year and all customers believe that I'm a kind of wizard or something) :D

**Comment by chkr1011** [comment]
No worries. I will close this pull request for now because I will adapt the changes you made in the branch which contains the 4.0.0 version of the library.

**Comment by SeppPenner** [comment]
> No worries. I will close this pull request for now because I will adapt the changes you made in the branch which contains the 4.0.0 version of the library.

Okay :)

**Pull request closed without merging**
