### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by JanEggers**
like discussed in #93

### CODE REVIEW

**Comment by chkr1011** [comment]
1. Is assume also some changes for the factory using some #if are required because the interface is no longer used but the service provider class itself. So the parameters must be changed too. Or am I wrong and miss something?
2. Started event is a good idea! Can you please check my Wiki entry if it makes sense with the ASP.NET Core integration? And update if required?

**Comment by JanEggers** [comment]
> 1. 
no api is compatibe as we dont use the concreate return type but just System.IServiceProvider

>2. will do.

im also looking at the failing tests, the one that remains is a similar timing issue but i need access to the clientSession in order to verify presence of the WillMessage

**Comment by chkr1011** [comment]
Ah OK because I had to change it in my code. But anyway we will see 😄 
Yes I already saw it but I don't know why they fail. I saw that an exception is thrown which indicates that a port is already used by the system but the adapter is the test adapter only. I also tried to debug the failing tests with no luck.

**Comment by JanEggers** [comment]
so issue should be fixed now if you have a socket in use issue and dont know who is it use tcpview from sysinternals or netstat

**Comment by chkr1011** [comment]
I am wondering WHY the unit test want's to open a socket. Due to the test server adapter there should be no attempt to open one event if it is not used?!

**Comment by chkr1011** [comment]
Maybe you didn't noticed but I added you as a official contributor. You can create branches in this repository if you like.

**Comment by JanEggers** [comment]
> I am wondering WHY the unit test want's to open a socket. Due to the test server adapter there should be no attempt to open one event if it is not used?!

because i just add the testadapter to the list of adapters if tcp listener should not be present we have to remove it from the service collection

**Comment by chkr1011** [comment]
Ah that makes sense. How can it be removed?

You can still create pull request for merges. It is up to you to decide what you want to use 😄

**Comment by JanEggers** [comment]
my usual approch is adding this

```
        public static IServiceCollection RemoveAll<T>(this ServiceCollection services)
        {
            var toRemove = services.Where(s => s.ServiceType == typeof(T)).ToList();

            foreach (var serviceDescriptor in toRemove)
            {
                services.Remove(serviceDescriptor);
            }

            return services;
        }

         var services = new ServiceCollection()
                .AddLogging()
                .AddMqttServer()
                .RemoveAll<IMqttServerAdapter>()
                .AddSingleton<IMqttServerAdapter>(serverAdapter)
                .BuildServiceProvider();
```

**Pull request merged**
