### PR TITLE
added dependencies to nuspec and fixed build

### PR DESCRIPTION
**Pull request by JanEggers**
fixes build for #82

### CODE REVIEW

**Comment by chkr1011** [comment]
Isn't it required to add all libs? I added:
```
      <group targetFramework="netstandard1.3">
        <dependency id="NETStandard.Library" version="1.6.1" />
        
        <dependency id="Microsoft.Extensions.DependencyInjection" version="1.1.1" />
        <dependency id="Microsoft.Extensions.Logging" version="1.1.2" />
        <dependency id="Microsoft.Extensions.Logging.Abstractions" version="1.1.2" />
        <dependency id="Microsoft.Extensions.Options" version="1.1.2" />
        
        <dependency id="System.Net.Security" version="4.3.2" />
        <dependency id="System.Net.WebSockets" version="4.3.0" />
        <dependency id="System.Net.WebSockets.Client" version="4.3.1" />
        <dependency id="System.Threading" version="4.3.0" />
        <dependency id="System.Threading.Thread" version="4.3.0" />
      </group>
```

But I am not sure. I just added every lib which is references by the projects. Even if Options i.e. is a sub lib of the Logger one. 

I am also not sure if a group for targeting regular net framework is required. Because the DI stuff is not part of it.

**Comment by JanEggers** [comment]
i added the missing packages and verified with a console app.

image

> Even if Options i.e. is a sub lib of the Logger one.
no i just forgot options.

> I am also not sure if a group for targeting regular net framework is required. Because the DI stuff is not part of it.

net461 means it runs on net461 "Platform" but all packages not present in net461 must be delivered with the app. that is why system.* are not included in net461 but ms.extensions.di and logging are not present in net461 so they must be deployed with your app.

my app is ~30 mb deployment because of all the packages of aspnetcore and ms.extensions.* bring in my own assemblies are 100KB....

**Comment by JanEggers** [comment]
btw: should i check why the test is failing?

**Comment by JanEggers** [comment]
gaaa i explain it and did not fix it give me a second

**Comment by JanEggers** [comment]
now it should be good

**Comment by chkr1011** [comment]
So does it mean I have to add the extension libs on my own if I use NET461?

Yes please check the test. I just saw it too but I have no time yet to look at it. In general it looks good so it seems some internal problem.

**Comment by JanEggers** [comment]
i fixed the test and maybe introduced a new issue. i had to refactor retention manager so it comes from di so i get get it for testing. but for that i had to make it a singleton.

that implies if someone wants to start 2 servers he should create a serviceprovider for each one otherwise the singletons will overlap.

we can fix that if we make the retentionmanager scoped and begin a new scope in each server but i dont know if that is a reasonable change what do you think?

**Comment by chkr1011** [comment]
I think two servers in one process is not a use case at the moment. If so, we can change it after a request was made. I don't see any use case at the moment. Across processes OK but not in one process.

As usual, good job! 👍

**Pull request merged**
