### PR TITLE
Aspnetcore3bugfixes

### PR DESCRIPTION
**Pull request by JanEggers**

### CODE REVIEW

**Comment by JanEggers** [comment]
@chkr1011 you should really change the default branch to dev you merged a pr against master wich wasnt intended Ii guess.

**Comment by JanEggers** [comment]
fixed #758

**Comment by JanEggers** [comment]
we can now update the wiki: #865 if this gets accepted

**Comment by SeppPenner** [comment]
Ok, I will check this in detail tonight (hopefully).

**Comment by chkr1011** [comment]
Good work 👍 Please also update the nuget release notes. I am busy with my other projects so that I cannot collect all changes on my own before releasing a new version.
@JanEggers You can also merge on your own in urgent cases.

**Comment by chkr1011** [comment]
@JanEggers I will remove the develop branch soon. I am also fed up with this 😄

**Comment by chkr1011** [comment]
@JanEggers I removed the _develop_ branch. From now on we will only work on the master branch. I also fixed several build errors. So please pull the master branch in this feature branch.

**Pull request merged**
