### PR TITLE
Support for websockets

### PR DESCRIPTION
**Pull request by nowakpiotr**
Added a communication channel.

### CODE REVIEW

**Comment by chkr1011** [comment]
Hi,
very good job 👍 I will merge it and create a new release soon.
Best regards
Christian

**Comment by nowakpiotr** [comment]
Hi,
If the project has been upgraded to .net standard 2.0 it will be possible
to support wss. Can I do that ??

Pozdrawiam,
Piotr Nowak
+694 506 660

2017-09-01 10:08 GMT+02:00 Christian <notifications@github.com>:

**Comment by chkr1011** [comment]
This depends on the support of the required platforms. 
This project should run on Windows Linux and ARM Raspberry Pi. 
I don't know the status of .NET Core in detail but if those platforms are all supported by .net standard 2.0 you can upgrade.

**Comment by chkr1011** [comment]
Another question: Do you have any idea how to implement web socket support for the broker?

**Comment by nowakpiotr** [comment]
I think this is the way to go, but I would need some time to do it and test it

**Comment by chkr1011** [comment]
I will merge it and test it on my Pi too with .net standard 2.0. if all works I will create a new release. In my opinion this is the best way. Do you agree?

**Comment by nowakpiotr** [comment]
In my opinion that should work well.
https://blogs.msdn.microsoft.com/david/2017/07/20/setting_up_raspian_and_dotnet_core_2_0_on_a_raspberry_pi/

**Comment by chkr1011** [comment]
OK then just update it. I will test it before creating a new release. Do you have an idea to add at least one UnitTest? I know that we need a server for proper testing but maybe you have a different idea.

**Comment by chkr1011** [comment]
And please have a look at the code quality checks 😄

**Comment by nowakpiotr** [comment]
The Travis CI build failed. Do you know why ?

**Comment by chkr1011** [comment]
Yes I have to fix the travis config. It is only activated but the travis config file is missing

**Comment by chkr1011** [comment]
I will merge this. Please start a new pull request for WSS support...

**Comment by chkr1011** [comment]
Hi I refactored the WebSocket code a little bit. I hope you like it. I also added support for the other frameworks.

**Pull request merged**
