### PR TITLE
more extensions for aspnetcore configuration

### LINKED ISSUE #338: Implement ServiceCollectionExtensions.AddHostedMqttServer<TService>(this IServiceCollection services) to make the IMqttServerOptions injectable
curently, when use the asp.net core library, normally do following:

```
public void ConfigureServices(IServiceCollection services)
{
     var mqttServerOptions = new MqttServerOptionsBuilder().Build();
     services.AddHostedMqttServer(mqttServerOptions);
}
```

the mqttServerOptions will passed in as an instance and registered with DI container. Then resolved with MqttHostedServer as IMqttServerOptions.

If I want to make the IMqttServerOptions itself injectable, for example, IMqttServerOptions might depends on some settings and neededs to resolve the IOptions<> which might not be availabe at the ConfigureServices. Even though can find some work around. I thhink it would be better to add an extra extention method like this:

```
public static IServiceCollection AddHostedMqttServer<TService>(this IServiceCollection services) where TService: class, IMqttServerOptions
{          
    services.AddSingleton<IMqttServerOptions,TService>();
    services.AddSingleton<IMqttNetLogger>(new MqttNetLogger());
    services.AddSingleton<MqttHostedServer>();
    services.AddSingleton<IHostedService>(s => s.GetService<MqttHostedServer>());
    services.AddSingleton<IMqttServer>(s => s.GetService<MqttHostedServer>());
    services.AddSingleton<MqttWebSocketServerAdapter>();
    services.AddSingleton<MqttTcpServerAdapter>();
    services.AddSingleton<IMqttServerAdapter>(s => s.GetService<MqttWebSocketServerAdapter>());
    services.AddSingleton<IMqttServerAdapter>(s => s.GetService<MqttTcpServerAdapter>());
    return services;
}
```

Then I can have a class implement IMqttServerOptions:

 ```
public class MyMqttServerOptions : IMqttServerOptions
    {
	public MyMqttServerOptions(IOptions<MyMqttServerSettings> options)
	{
		....
	}
...
}

```

In the ConfigureServices

```
public void ConfigureServices(IServiceCollection services)
{
     ...
     services.AddHostedMqttServer<MyMqttServerOptions>();
}

```

### PR DESCRIPTION
**Pull request by JanEggers**
fixes #338, I will update the wiki if this is accepted. @liuhongbo do you have what you need with this or is there still something missing?

### CODE REVIEW

**Comment by chkr1011** [comment]
Good work 👍

**Comment by JanEggers** [comment]
should I update the wiki now or wait for 2.8 to be final?

**Comment by chkr1011** [comment]
I hope that the final will be released this weekend 😄 So you can already update it. This is better than forgetting it.

**Comment by liuhongbo** [comment]
Good work.  even better than what I was looking for!  👍

**Pull request merged**
