### PR TITLE
.Net5.0 TFMs added

### PR DESCRIPTION
**Pull request by StefanOssendorf**
This adds the .Net5.0 TFM to all project and related nuget packages are updated.

**BUT** sadly I could not run any tests since I always got a socket related exception and I don't know why.
Furthermore I could not build the `MQTTnet.TestApp.AspNetCore2` project with the following error: 
`TS2307	Build:Cannot find module 'mqtt' or its corresponding type declarations.	MQTTnet.TestApp.AspNetCore2`

### CODE REVIEW

**Comment by JanEggers** [comment]
I will have alook at it now that 5.0 is out im ager to update too :)

**Comment by StefanOssendorf** [comment]
Great :-)
And just to reference the issue #1017

**Comment by JanEggers** [comment]
Hi @StefanOssendorf I rebased your changes and modified some ifdefs

the current state wass building for me but some tests are failing. @chkr1011 should the tests be green or are there some expected red dots?

**Comment by chkr1011** [comment]
@JanEggers On my machine all tests are green. I am still trying to fix them in our CI but it seems that the server has some limitations which end up in broken tests (CPU, RAM etc.). But they should also run all on your machine as well.

Ich tests are failing?

**Comment by JanEggers** [comment]
the same as in the ci run are failing on my machine.

 Failed Connect_To_Invalid_Server_Wrong_IP [2 s]
  Error Message:
   Test method threw exception System.OperationCanceledException, but exception MQTTnet.Exceptions.MqttCommunicationTimedOutException was expected. Exception message: System.OperationCanceledException: The operation was canceled.


 Try_Connect_Invalid_Host [3 s]
  Error Message:
   Test method MQTTnet.Tests.CrossPlatformSocket_Tests.Try_Connect_Invalid_Host threw exception: 
System.Net.Sockets.SocketException: The I/O operation has been aborted because of either a thread exit or an application request.

**Comment by chkr1011** [comment]
These are OK from my point of view. I will merge this soon and see how to patch the tests so they will work as usual. Still wondering why ALL tests are green on my machine!?

**Pull request merged**
