### PR TITLE
Fix for ignored certificate information

### PR DESCRIPTION
**Pull request by cvellan**
_tlsOptions was never assigned when building an instance of MqttClientOptions using an MQttClientOptionsBuilder, and certificate information was being lost.

This was a part of the cause of issue #115.

### CODE REVIEW

**Comment by chkr1011** [comment]
Hi, 
please fix the conflicts. Then I will merge the pull request.
Best regards
Christian

**Comment by cvellan** [comment]
I did try to fix it but seem to have made more of a mess of things; I'm unused to the pull request process. Sorry for the hassle.

The effective changes are lines 122 and 126, where the TlsOptions of the active channeloptions needs to be set, instead of setting the channel options themselves (as that also happens later at line 130).

I'll try to fix the code up, if not I'll submit a clean PR. Or feel free to do it yourself if it takes too long.

**Comment by chkr1011** [comment]
Don't worry. I will fix the bug on my own. With the previous pull request you are added to the contributor list 😄

**Comment by cvellan** [comment]
Glad I could help! 😃

**Pull request closed without merging**
