### PR TITLE
Windows 7 support

### LINKED ISSUE #548: Windows 7 websockets support
Hi folks,

i'm developing an application who sends data from my android application to a desktop PC. First it worked on local network at home with no port restrictions. (without mqtt)

Now i need this application for my workstation at work. This is a Windows 7 PC behind a McAfee (uargh) firewall (i guess there is only port 80 open).

I decided to use mqtt to transmit the needed data over my raspberry pi. On the pi there is already a nginx webserver, so port 80 is in use and cannot take it for mosquitto broker. So i need to use websockets for this situation, BUT Windows 7 cannot use System.Net.Websockets.Client. I think this issue is already known.

Is it possible to use System.Net.Websockets.Client.Managed in MQTTnet? I already testet it, and it seems to work fine.

What do you think about it? Or did i miss something that MQTTnet already supports Windows 7 clients?

Thanks in advance!
Regards...

### PR DESCRIPTION
**Pull request by matthid**
Fixes #548, which has been closed but is still an issue for us.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Hi @matthid. I closed the issue because I wasn't sure if it is still a problem (and it was actually quite old `11 Feb` and used an old version of MQTTnet). Fore me this looks valid, I cannot try it on Windows 7 because I don't have Windows 7 anymore. @chkr1011 Please check this and merge it if you think it's valid ;)

**Comment by matthid** [comment]
@SeppPenner I understand, just one note: 'public' people cannot reopen an issue so they can decide to open a new one or comment in a closed one to prevent duplicates

Regarding this PR yes that matthid prefix in the package is strage, but at least it is honest. The alternative https://www.nuget.org/packages/System.Net.WebSockets.Client.Managed/ looks unmaintained to me and actually was maintained by someone random on the internet as well :) The problem with this package is that it is not strong named so I basically just rebuild and strong named it so mqttnet can still be strong named

I'm open to suggestions ;)

**Comment by SeppPenner** [comment]
@matthid I have already seen your project.

> The problem with this package is that it is not strong named so I basically just rebuild and strong named it so mqttnet can still be strong named

I already assumed that this was the reason.

I will leave this PR for Christian to decide what he wants to do as he is the owner of the project.

**Comment by matthid** [comment]
To add a couple of options of what we could do:
- Inline the dependency here and sign with your key
- Rename the package to something without `matthid-`
- Something else (like ignoring win7 support, which wouldn't help us ...)

**Comment by chkr1011** [comment]
Hi @matthid,
thank you for your contribution and interest in this project.

I would rather not accept that merge request. The reason is that you add a dependency to your project (as nuget) which cannot be maintained by us. One goal of this lib is to avoid other dependencies as much as possible. That is also the reason why we have no DI or Rx in place. 

But to get a fix for Windows 7 I recommend that you build another project and nuget which can be used in **combination** with MQTTnet. Please have a look at the extension for _WebSocket4Net_. I assume your fix can be implemented in a similar way. Then you can maintain that extension on your own or you add this extension to this repo (respecting the exiting naming conventions etc.). This is up to you.

What do you think about this solution?

Best regards
Christian

**Comment by matthid** [comment]
I took a quick look and indeed this might work, I'd have to implement a lot of interfaces but it should do. Will try and report back here.

**Comment by chkr1011** [comment]
Why "a lot of interfaces"? I assume it should be 2 or 3. Please checkout the existing extension for WebSocket4Net. Basically you can copy most of it.

**Comment by matthid** [comment]
@chkr1011 Yes, it looks like it works. Thanks for the idea and the new APIs (they were not available on the version we signed and used internally). We could potentially document this somewhere if you want.

> Why "a lot of interfaces"? 

Maybe not a lot of interfaces, but all are basically just a copy of the existing code:

`IMqttChannel` / `MqttWebSocketChannel` -> The actual change
`IMqttServerAdapter` / `MqttWebSocketServerAdapter` -> For the server
`IMqttClientAdapterFactory` / `MqttClientAdapterFactory` -> For the client

You can then use `IMqttFactory.UseClientAdapterFactory` on the client and inject the `ServerAdapter` on the server.

**Pull request closed without merging**
