### PR TITLE
Targetframeworkfix

### PR DESCRIPTION
**Pull request by JanEggers**
this pr should improve #100

### CODE REVIEW

**Comment by chkr1011** [comment]
Thanks for fixing that issue. I will wait a couple of days and also fix two exceptions I found. Then I will release it as 2.5.2. Do you agree?

**Comment by JanEggers** [comment]
yup agreed. i still have the issue open in dotnetstandard repo because i still dont fully understand whats going on.

**Comment by JanEggers** [comment]
maybee we have to remove the nuget config again as it is causing appveyor to fail

**Comment by chkr1011** [comment]
Mhh strange thing...

**Pull request merged**
