### PR TITLE
Client cancel task

### PR DESCRIPTION
**Pull request by acrabb**
Hello hello,

Our team was seeing many unhandled exceptions being thrown from within the MQTT library. Many seem to be a Mono issue. Others were fixed by ensuring a Task is canceled even if its getting disposed.

Please see PR and review 👍

### CODE REVIEW

**Comment by chkr1011** [comment]
@acrabb Hi, thank you for your contribution. I am on a workshop at the moment. So I cannot review it. But I hope to do it at the upcoming weekend. So far I can see no issues with it. One thing is maybe regarding the parameter for the "Cancel" method. I usually use "false" to get an aggregate exception instead of the first one.

**Comment by JanEggers** [comment]
@acrabb check your spacing settings please and add a testcase for what you want to fix

**Comment by chkr1011** [comment]
Good work 👍 I will release a new version soon (probably sunday...)

**Comment by acrabb** [comment]
Thank you.
Did you still want the unit test?

**Pull request merged**
