### PR TITLE
UnobservedTaskExceptions from a TaskCompletionSource in 2.8.3

### PR DESCRIPTION
**Pull request by MatthewTheThomas**
Hello,

With the 2.8.3 release of MQTTnet, our team noticed additional unobserved task exceptions being thrown from within the MQTT library. After looking into it, we found the issue to be a TaskCompletionSource that is never observed. 

This PR replaces the _disconnectReason TaskCompletionSource with a SemaphoreSlim since the tcs is never observed so each time it is disposed it will throw an UnobservedTaskException. The SemaphoreSlim is perhaps overkill when a bool would do it, but it should technically be more thread-safe (and it's less lines of code).

### CODE REVIEW

**Comment by chkr1011** [comment]
Hi, thank you for your contribution. I released 2.8.4-rc1 which includes a fix. I assume that your RP is no longer required. 

Or do you see any issues in my fix?

Best regards
Christian

**Comment by MatthewTheThomas** [comment]
@chkr1011 	I just checked using the 2.8.4-rc1 and it's exhibiting the same behaviors with regards to the UnobservedTaskExceptions caused by `_disconnectReason`.

**Comment by chkr1011** [comment]
Ah OK now I got it. I fixed another issue 😄 In my opinion the semaphore is too heavy as you already said. I am testing an approach with an interlocked int at the moment.

**Comment by chkr1011** [comment]
I released 2.8.4-rc2. Please let me know if this version works for you.

**Comment by MatthewTheThomas** [comment]
@chkr1011 Perfect! That fixes it. Thanks!

**Pull request closed without merging**
