### PR TITLE
fixed parallel writes

### LINKED ISSUE #468: concurrent send is not allowed with newer pipelines package
with the new package aspnet core dependencies im seeing concurrency exceptions in the aspnet.connections based transport. 

I assume it was broken before but the transport did not complaint if there was an issue.

### PR DESCRIPTION
**Pull request by JanEggers**
fixes #468

### CODE REVIEW

**Comment by JanEggers** [comment]
@chkr1011 hi christian, can you please check asap and generate a new verssion as this kind of bug is quite critical

**Comment by JanEggers** [comment]
@chkr1011 build seems not to be running because your cert expired ?!

**Comment by chkr1011** [comment]
Also please review my task await.

**Comment by JanEggers** [comment]
thx for configure await false do you know if there is a roslyn analyser that generates errors for this as I keep forget to add it....

**Comment by chkr1011** [comment]
Sorry but I don't know one. But you have me as a fallback 😄 I upload 2.8.5-rc2 in a few minutes.

**Comment by JTrotta** [comment]
@JanEggers May it be your are looking for this one [http://www.learnasync.net/](url) ?

**Pull request merged**
